version: '3.8'

services:
  nginx:
    image: nginx:alpine
    container_name: somniaID-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl:/etc/nginx/ssl
    depends_on:
      - frontend
      - backend
    networks:
      - somniaID-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    container_name: somniaID-frontend-prod
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=https://api.somniaID.com
      - NEXT_PUBLIC_CONTRACT_ADDRESS=${CONTRACT_ADDRESS}
    networks:
      - somniaID-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    container_name: somniaID-backend-prod
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - MONGODB_URI=${MONGODB_URI}
      - JWT_SECRET=${JWT_SECRET}
      - FRONTEND_URL=https://somniaID.com
    networks:
      - somniaID-network

  redis:
    image: redis:alpine
    container_name: somniaID-redis
    restart: unless-stopped
    volumes:
      - redis_data:/data
    networks:
      - somniaID-network

volumes:
  redis_data:


networks:
  somniaID-network:
    driver: bridge
